.Dd January 21, 2022
.Dt luksdeinfo
.Os libluksde
.Sh NAME
.Nm luksdeinfo
.Nd determines information about a Linux Unified Key Setup (LUKS) Disk Encryption volume
.Sh SYNOPSIS
.Nm luksdeinfo
.Op Fl k Ar key
.Op Fl o Ar offset
.Op Fl p Ar password
.Op Fl huvV
.Ar source
.Sh DESCRIPTION
.Nm luksdeinfo
is a utility to determine information about a Linux Unified Key Setup (LUKS) Disk Encryption volume
.Pp
.Nm luksdeinfo
is part of the
.Nm libluksde
package.
.Nm libluksde
is a library to access the Linux Unified Key Setup (LUKS) Disk Encryption format
.Pp
.Ar source
is the source file.
.Pp
The options are as follows:
.Bl -tag -width Ds
.It Fl h
shows this help
.It Fl k Ar key
specify the volume master key formatted in base16
.It Fl o Ar offset
specify the volume offset
.It fl p Ar password
specify the password
.It Fl u
unattended mode (disables user interaction)
.It Fl v
verbose output to stderr
.It Fl V
print version
.El
.Sh ENVIRONMENT
None
.Sh FILES
None
.Sh EXAMPLES
.Bd -literal
# luksdeinfo -p Password /dev/sda1
luksdeinfo 20130704
.sp
Linux Unified Key Setup Disk Encryption information:
	Encryption method:		AES 128-bit
.sp
.Ed
.Sh DIAGNOSTICS
Errors, verbose and debug output are printed to stderr when verbose output \-v is enabled.
Verbose and debug output are only printed when enabled at compilation.
.Sh BUGS
Please report bugs of any kind to <joachim.metz@gmail.com> or on the project website:
https://github.com/libyal/libluksde/
.Sh AUTHOR
These man pages were written by Joachim Metz.
.Sh COPYRIGHT
Copyright (C) 2013-2022, Joachim Metz <joachim.metz@gmail.com>.
This is free software; see the source for copying conditions. There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
.Sh SEE ALSO
.Xr luksdemount 1
